import React,{useEffect,useState} from "react";
import {View,Text,StyleSheet,TextInput,TouchableOpacity,Alert,ActivityIndicator} from "react-native";
import {useLocalSearchParams,useRouter} from "expo-router";
import {useQueryClient} from "@tanstack/react-query";
import {useColors} from "@/hooks/useColors";
import {formatDateDDMMYY,ddmmyyToISO} from "@/lib/dateFormat";
import {getToken} from "@/lib/apiToken";
import {useGetInvoice,getGetInvoicesQueryKey,getGetDashboardStatsQueryKey} from "@workspace/api-client-react";
import {KeyboardAwareScrollViewCompat} from "@/components/KeyboardAwareScrollViewCompat";
const API_BASE=`https://${process.env.EXPO_PUBLIC_DOMAIN||"pharma-pay-tracker.onrender.com"}`;
export default function EditInvoice(){const {id}=useLocalSearchParams<{id:string}>();const invoiceId=Number(id);const colors=useColors();const router=useRouter();const qc=useQueryClient();const {data:inv,isLoading}=useGetInvoice(invoiceId);const [num,setNum]=useState("");const [date,setDate]=useState("");const [amount,setAmount]=useState("");const [due,setDue]=useState("");const [saving,setSaving]=useState(false);
useEffect(()=>{if(inv){setNum(inv.invoiceNumber);setDate(formatDateDDMMYY(inv.invoiceDate));setAmount(String(inv.billAmount));setDue(formatDateDDMMYY(inv.dueDate));}},[inv]);
const save=async()=>{const invoiceDate=ddmmyyToISO(date),dueDate=ddmmyyToISO(due),billAmount=Number(amount);if(!num.trim()||!invoiceDate||!dueDate||!billAmount||billAmount<=0)return Alert.alert("Validation","Enter valid invoice number, DD-MM-YY dates and amount.");setSaving(true);try{const token=getToken();const r=await fetch(`${API_BASE}/api/invoices/${invoiceId}`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({invoiceNumber:num.trim(),invoiceDate,billAmount,dueDate})});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||"Failed to edit invoice");qc.invalidateQueries({queryKey:getGetInvoicesQueryKey()});qc.invalidateQueries({queryKey:getGetDashboardStatsQueryKey()});qc.invalidateQueries({queryKey:["/api/invoices",invoiceId]});Alert.alert("Updated","Invoice updated successfully.",[{text:"OK",onPress:()=>router.back()}]);}catch(e:any){Alert.alert("Error",e?.message||"Failed to edit invoice");}finally{setSaving(false)}};
if(isLoading)return <View style={[s.center,{backgroundColor:colors.background}]}><ActivityIndicator color={colors.primary}/></View>;const input=[s.input,{backgroundColor:colors.card,borderColor:colors.border,color:colors.foreground}];return <View style={[s.container,{backgroundColor:colors.background}]}><KeyboardAwareScrollViewCompat contentContainerStyle={s.content}><Text style={[s.note,{color:colors.mutedForeground}]}>Store cannot be changed here. Editing bill amount preserves amounts already paid.</Text><Text style={[s.label,{color:colors.mutedForeground}]}>Invoice Number</Text><TextInput style={input} value={num} onChangeText={setNum}/><Text style={[s.label,{color:colors.mutedForeground}]}>Invoice Date (DD-MM-YY)</Text><TextInput style={input} value={date} onChangeText={setDate} keyboardType="numbers-and-punctuation"/><Text style={[s.label,{color:colors.mutedForeground}]}>Bill Amount (₹)</Text><TextInput style={input} value={amount} onChangeText={setAmount} keyboardType="numeric"/><Text style={[s.label,{color:colors.mutedForeground}]}>Due Date (DD-MM-YY)</Text><TextInput style={input} value={due} onChangeText={setDue} keyboardType="numbers-and-punctuation"/><TouchableOpacity style={[s.btn,{backgroundColor:colors.primary},saving&&{opacity:.6}]} onPress={save} disabled={saving}>{saving?<ActivityIndicator color="#fff"/>:<Text style={s.btnText}>Save Changes</Text>}</TouchableOpacity></KeyboardAwareScrollViewCompat></View>}
const s=StyleSheet.create({container:{flex:1},center:{flex:1,alignItems:"center",justifyContent:"center"},content:{padding:20,gap:8},note:{fontSize:12,lineHeight:17,marginBottom:8},label:{fontSize:12,fontFamily:"Inter_500Medium",marginTop:6},input:{borderWidth:1,borderRadius:10,paddingHorizontal:12,paddingVertical:11,fontSize:14},btn:{marginTop:16,borderRadius:12,paddingVertical:14,alignItems:"center"},btnText:{color:"#fff",fontFamily:"Inter_600SemiBold",fontSize:15}});