import { Router } from "express";
import { db, customersTable, invoicesTable } from "@workspace/db";
import { eq, and, ilike, sql, desc, gte, lte } from "drizzle-orm";
import { requireAuth, AuthRequest } from "../middlewares/authMiddleware";
const router=Router();router.use(requireAuth as any);
function autoStatus(outstanding:number,bill:number,due:string){const today=new Date().toISOString().split("T")[0];if(outstanding<=0)return"paid";if(outstanding<bill)return"partial";if(due<today)return"overdue";return"pending";}
router.get("/",async(req:AuthRequest,res)=>{try{const{search,status,customerId,fromDate,toDate}=req.query;const c:any[]=[];if(customerId)c.push(eq(invoicesTable.customerId,parseInt(customerId as string)));if(status)c.push(eq(invoicesTable.status,status as string));if(fromDate)c.push(gte(invoicesTable.invoiceDate,fromDate as string));if(toDate)c.push(lte(invoicesTable.invoiceDate,toDate as string));const rows=await db.select({id:invoicesTable.id,customerId:invoicesTable.customerId,customerName:customersTable.name,invoiceNumber:invoicesTable.invoiceNumber,invoiceDate:invoicesTable.invoiceDate,billAmount:invoicesTable.billAmount,dueDate:invoicesTable.dueDate,outstandingBalance:invoicesTable.outstandingBalance,status:invoicesTable.status,createdAt:invoicesTable.createdAt}).from(invoicesTable).innerJoin(customersTable,eq(invoicesTable.customerId,customersTable.id)).where(and(...c,search?ilike(sql`CONCAT(${customersTable.name}, ' ', ${invoicesTable.invoiceNumber})`,`%${search}%`):undefined)).orderBy(desc(invoicesTable.invoiceDate));res.json(rows.map(r=>({...r,billAmount:Number(r.billAmount),outstandingBalance:Number(r.outstandingBalance)})));}catch(err){req.log?.error({err},"Failed to list invoices");res.status(500).json({error:"Failed to fetch invoices"});}});
router.post("/",async(req:AuthRequest,res)=>{try{const{customerId,invoiceNumber,invoiceDate,billAmount,dueDate}=req.body;const status=dueDate<new Date().toISOString().split("T")[0]?"overdue":"pending";const[invoice]=await db.insert(invoicesTable).values({customerId,invoiceNumber,invoiceDate,billAmount:String(billAmount),dueDate,outstandingBalance:String(billAmount),status}).returning();const[customer]=await db.select({name:customersTable.name}).from(customersTable).where(eq(customersTable.id,customerId));res.status(201).json({...invoice,customerName:customer?.name||"",billAmount:Number(invoice.billAmount),outstandingBalance:Number(invoice.outstandingBalance)});}catch(err){req.log?.error({err},"Failed to create invoice");res.status(500).json({error:"Failed to create invoice"});}});
router.get("/:id",async(req:AuthRequest,res)=>{try{const id=parseInt(req.params.id);const[row]=await db.select({id:invoicesTable.id,customerId:invoicesTable.customerId,customerName:customersTable.name,invoiceNumber:invoicesTable.invoiceNumber,invoiceDate:invoicesTable.invoiceDate,billAmount:invoicesTable.billAmount,dueDate:invoicesTable.dueDate,outstandingBalance:invoicesTable.outstandingBalance,status:invoicesTable.status,createdAt:invoicesTable.createdAt}).from(invoicesTable).innerJoin(customersTable,eq(invoicesTable.customerId,customersTable.id)).where(eq(invoicesTable.id,id));if(!row)return res.status(404).json({error:"Invoice not found"});res.json({...row,billAmount:Number(row.billAmount),outstandingBalance:Number(row.outstandingBalance)});}catch(err){req.log?.error({err},"Failed to get invoice");res.status(500).json({error:"Failed to fetch invoice"});}});
router.patch("/:id",async(req:AuthRequest,res)=>{try{const id=parseInt(req.params.id);const[old]=await db.select().from(invoicesTable).where(eq(invoicesTable.id,id));if(!old)return res.status(404).json({error:"Invoice not found"});const oldBill=Number(old.billAmount),oldOutstanding=Number(old.outstandingBalance),paid=Math.max(0,oldBill-oldOutstanding);const newBill=req.body.billAmount!==undefined?Number(req.body.billAmount):oldBill;if(!Number.isFinite(newBill)||newBill<=0)return res.status(400).json({error:"Invalid bill amount"});if(newBill<paid)return res.status(400).json({error:`Bill amount cannot be less than already paid amount ₹${paid.toFixed(2)}`});const newDue=req.body.dueDate??old.dueDate;const newOutstanding=Math.max(0,newBill-paid);const updates:any={outstandingBalance:String(newOutstanding),status:autoStatus(newOutstanding,newBill,newDue)};if(req.body.invoiceNumber!==undefined)updates.invoiceNumber=req.body.invoiceNumber;if(req.body.invoiceDate!==undefined)updates.invoiceDate=req.body.invoiceDate;if(req.body.billAmount!==undefined)updates.billAmount=String(newBill);if(req.body.dueDate!==undefined)updates.dueDate=req.body.dueDate;const[updated]=await db.update(invoicesTable).set(updates).where(eq(invoicesTable.id,id)).returning();const[customer]=await db.select({name:customersTable.name}).from(customersTable).where(eq(customersTable.id,updated.customerId));res.json({...updated,customerName:customer?.name||"",billAmount:Number(updated.billAmount),outstandingBalance:Number(updated.outstandingBalance)});}catch(err){req.log?.error({err},"Failed to update invoice");res.status(500).json({error:"Failed to update invoice"});}});
router.delete("/:id",async(req:AuthRequest,res)=>{try{await db.delete(invoicesTable).where(eq(invoicesTable.id,parseInt(req.params.id)));res.json({success:true,message:"Invoice deleted"});}catch(err){req.log?.error({err},"Failed to delete invoice");res.status(500).json({error:"Failed to delete invoice"});}});
export default router;
