import React, { useMemo, useState } from "react";
import { ActivityIndicator, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useQuery } from "@tanstack/react-query";
import { Feather } from "@expo/vector-icons";
import { useColors } from "@/hooks/useColors";
import { medpayApi, MonthlyRegister, RegisterAgency } from "@/lib/medpayApi";

const money=(n:number)=>`₹${Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:2})}`;
const monthKey=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;
const monthLabel=(key:string)=>new Date(`${key}-01T00:00:00`).toLocaleDateString("en-IN",{month:"long",year:"numeric"});

export default function MonthlyRegisterScreen(){
 const {customerId,customerName}=useLocalSearchParams<{customerId:string;customerName?:string}>();
 const id=Number(customerId),colors=useColors(),router=useRouter(),isDesktop=Platform.OS==="web";
 const[month,setMonth]=useState(monthKey(new Date())),[search,setSearch]=useState(""),[filter,setFilter]=useState("all");
 const query=useQuery({queryKey:["monthly-register",id,month],queryFn:()=>medpayApi<MonthlyRegister>(`/api/monthly-register/${id}?month=${month}`)});
 const move=(by:number)=>{const d=new Date(`${month}-01T00:00:00`);d.setMonth(d.getMonth()+by);setMonth(monthKey(d))};
 const rows=useMemo(()=>(query.data?.agencies||[]).filter(a=>a.agencyName.toLowerCase().includes(search.trim().toLowerCase())&&(filter==="all"||a.status===filter)),[query.data,search,filter]);
 const open=(a:RegisterAgency)=>router.push({pathname:"/register/agency",params:{customerId:String(id),customerName:customerName||"",agencyId:String(a.agencyId),agencyName:a.agencyName,month}} as any);
 const sum=query.data?.summary;
 return <View style={[s.page,{backgroundColor:colors.background}]}><ScrollView contentContainerStyle={s.content}>
  <Text style={[s.store,{color:colors.mutedForeground}]}>{customerName||"Medical Store"}</Text>
  <View style={[s.monthBar,{backgroundColor:colors.card,borderColor:colors.border}]}><TouchableOpacity onPress={()=>move(-1)}><Feather name="chevron-left" size={24} color={colors.primary}/></TouchableOpacity><View style={s.monthCenter}><Text style={[s.month,{color:colors.foreground}]}>{monthLabel(month)}</Text><Text style={[s.monthHint,{color:colors.mutedForeground}]}>Bill date ke according</Text></View><TouchableOpacity onPress={()=>move(1)}><Feather name="chevron-right" size={24} color={colors.primary}/></TouchableOpacity></View>
  {query.isLoading?<ActivityIndicator color={colors.primary} style={{margin:40}}/>:query.isError?<Text style={{color:colors.destructive,textAlign:"center"}}>Register load nahi hua. Retry karein.</Text>:<>
   <View style={s.summary}>{[["Agencies",sum?.totalAgencies],["Bills",sum?.totalBills],["Bill Amount",money(sum?.totalBillAmount||0)],["Paid",money(sum?.totalPaid||0)],["Remaining",money(sum?.totalRemaining||0)]].map(([l,v])=><View key={String(l)} style={[s.sumCard,{backgroundColor:colors.card,borderColor:colors.border}]}><Text style={[s.sumValue,{color:l==="Remaining"?colors.overdue:colors.foreground}]}>{v}</Text><Text style={[s.sumLabel,{color:colors.mutedForeground}]}>{l}</Text></View>)}</View>
   <View style={[s.search,{backgroundColor:colors.card,borderColor:colors.border}]}><Feather name="search" size={18} color={colors.mutedForeground}/><TextInput value={search} onChangeText={setSearch} placeholder="Search Agency" placeholderTextColor={colors.mutedForeground} style={{flex:1,color:colors.foreground}}/></View>
   <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}>{[["all","All"],["outstanding","Outstanding"],["partial","Partially Paid"],["paid","Paid / Clear"]].map(([k,l])=><TouchableOpacity key={k} onPress={()=>setFilter(k)} style={[s.chip,{borderColor:filter===k?colors.primary:colors.border,backgroundColor:filter===k?colors.primary:colors.card}]}><Text style={{color:filter===k?"#fff":colors.mutedForeground,fontFamily:"Inter_600SemiBold",fontSize:12}}>{l}</Text></TouchableOpacity>)}</ScrollView>
   {isDesktop&&<View style={[s.tableHead,{borderColor:colors.border}]}>{["Agency","Bills","Total","Paid","Baki","Status"].map(x=><Text key={x} style={[s.th,{color:colors.mutedForeground}]}>{x}</Text>)}</View>}
   {rows.length===0?<Text style={[s.empty,{color:colors.mutedForeground}]}>Is month/filter me koi agency bill nahi hai.</Text>:rows.map(a=><TouchableOpacity key={a.agencyId} onPress={()=>open(a)} style={[isDesktop?s.row:s.card,{backgroundColor:colors.card,borderColor:colors.border}]}>{isDesktop?<><Text style={[s.td,s.agency,{color:colors.foreground}]}>{a.agencyName}</Text><Text style={[s.td,{color:colors.foreground}]}>{a.totalBills}</Text><Text style={[s.td,{color:colors.foreground}]}>{money(a.totalBillAmount)}</Text><Text style={[s.td,{color:colors.paid}]}>{money(a.totalPaid)}</Text><Text style={[s.td,{color:colors.overdue}]}>{money(a.totalRemaining)}</Text><Text style={[s.td,{color:a.status==="paid"?colors.paid:a.status==="partial"?"#F59E0B":colors.overdue}]}>{a.status==="paid"?"✓ Clear":a.status==="partial"?"Partially Paid":"Outstanding"}</Text></>:<><View style={s.cardTop}><Text style={[s.agency,{color:colors.foreground}]}>{a.agencyName}</Text><Text style={{color:a.status==="paid"?colors.paid:a.status==="partial"?"#F59E0B":colors.overdue,fontFamily:"Inter_600SemiBold"}}>{a.status==="paid"?"✓ Clear":a.status==="partial"?"Partially Paid":"Outstanding"}</Text></View><Text style={{color:colors.mutedForeground}}>Bills: {a.totalBills} · Total: {money(a.totalBillAmount)}</Text><View style={s.amounts}><Text style={{color:colors.paid}}>Paid: {money(a.totalPaid)}</Text><Text style={{color:colors.overdue}}>Baki: {money(a.totalRemaining)}</Text></View></>}</TouchableOpacity>)}
  </>}
 </ScrollView></View>
}
const s=StyleSheet.create({page:{flex:1},content:{padding:16,gap:12,paddingBottom:40},store:{fontSize:13},monthBar:{borderWidth:1,borderRadius:14,padding:12,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},monthCenter:{alignItems:"center"},month:{fontSize:18,fontFamily:"Inter_700Bold"},monthHint:{fontSize:10,marginTop:2},summary:{flexDirection:"row",flexWrap:"wrap",gap:8},sumCard:{borderWidth:1,borderRadius:12,padding:12,minWidth:120,flexGrow:1},sumValue:{fontSize:17,fontFamily:"Inter_700Bold"},sumLabel:{fontSize:11,marginTop:3},search:{borderWidth:1,borderRadius:12,paddingHorizontal:12,flexDirection:"row",alignItems:"center",gap:8},filters:{gap:8},chip:{paddingHorizontal:14,paddingVertical:9,borderRadius:20,borderWidth:1},tableHead:{flexDirection:"row",borderBottomWidth:1,padding:12},th:{flex:1,fontSize:11,fontFamily:"Inter_600SemiBold"},row:{flexDirection:"row",borderWidth:1,borderRadius:10,padding:14,alignItems:"center"},td:{flex:1,fontSize:13},agency:{fontFamily:"Inter_700Bold",fontSize:15},card:{borderWidth:1,borderRadius:14,padding:15,gap:9},cardTop:{flexDirection:"row",justifyContent:"space-between",gap:8},amounts:{flexDirection:"row",justifyContent:"space-between"},empty:{textAlign:"center",padding:30}});
