import React from "react";
import { ActivityIndicator, Platform, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useQuery } from "@tanstack/react-query";
import { useColors } from "@/hooks/useColors";
import { medpayApi } from "@/lib/medpayApi";
import { formatDateDDMMYY } from "@/lib/dateFormat";
const money=(n:number)=>`₹${Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:2})}`;
type Bill={id:number;invoiceNumber:string;invoiceDate:string;billAmount:number;paidAmount:number;remainingAmount:number;paymentDate?:string;slipNumber?:string;agencyName:string;storeName:string};
export default function AgencyBills(){const p=useLocalSearchParams<{agencyId:string;agencyName:string;month:string}>(),colors=useColors(),router=useRouter(),desktop=Platform.OS==="web";const q=useQuery({queryKey:["global-agency-register",p.agencyId,p.month],queryFn:()=>medpayApi<{bills:Bill[]}>(`/api/monthly-register/agency/${p.agencyId}?month=${p.month}`)});return <View style={[s.page,{backgroundColor:colors.background}]}><ScrollView contentContainerStyle={s.content}><Text style={[s.title,{color:colors.foreground}]}>{p.agencyName} — {new Date(`${p.month}-01`).toLocaleDateString("en-IN",{month:"long",year:"numeric"})}</Text><Text style={{color:colors.mutedForeground}}>All Medical Stores</Text>{q.isLoading?<ActivityIndicator color={colors.primary}/>:!(q.data?.bills||[]).length?<Text style={{color:colors.mutedForeground,padding:30,textAlign:"center"}}>No bills</Text>:(q.data?.bills||[]).map((b,i)=><TouchableOpacity key={b.id} onPress={()=>router.push(`/invoice/${b.id}`)} style={[desktop?s.row:s.card,{backgroundColor:colors.card,borderColor:colors.border}]}>{desktop?<><Text style={s.cell}>{i+1}</Text><Text style={s.cell}>{b.storeName}</Text><Text style={s.cell}>{b.invoiceNumber}</Text><Text style={s.cell}>{formatDateDDMMYY(b.invoiceDate)}</Text><Text style={s.cell}>{money(b.billAmount)}</Text><Text style={[s.cell,{color:colors.paid}]}>{money(b.paidAmount)}</Text><Text style={[s.cell,{color:colors.overdue}]}>{money(b.remainingAmount)}</Text></>:<><Text style={[s.bill,{color:colors.foreground}]}>{b.storeName}</Text><Text style={{color:colors.foreground}}>Bill #{b.invoiceNumber}</Text><Text style={{color:colors.mutedForeground}}>{formatDateDDMMYY(b.invoiceDate)} · Amount {money(b.billAmount)}</Text><View style={s.line}><Text style={{color:colors.paid}}>Paid {money(b.paidAmount)}</Text><Text style={{color:colors.overdue}}>Baki {money(b.remainingAmount)}</Text></View><Text style={{color:colors.mutedForeground,fontSize:11}}>Payment: {b.paymentDate?formatDateDDMMYY(b.paymentDate):"—"} · Slip: {b.slipNumber||"—"}</Text></>}</TouchableOpacity>)}</ScrollView></View>}
const s=StyleSheet.create({page:{flex:1},content:{padding:16,gap:10,paddingBottom:40},title:{fontSize:20,fontFamily:"Inter_700Bold"},row:{flexDirection:"row",borderWidth:1,borderRadius:10,padding:12},cell:{flex:1,fontSize:12},card:{borderWidth:1,borderRadius:13,padding:14,gap:7},bill:{fontSize:15,fontFamily:"Inter_700Bold"},line:{flexDirection:"row",justifyContent:"space-between"}});
